### PR TITLE
[Hermes] Bump Hermes

### LINKED ISSUE #43633: React Native 0.74.0-rc.4: `use_ccache` is broken: no ccache wrapper script `ccache-clang.sh` bundled in npm package
### Description

if `use_ccache`, it would find wrapper scripts in this path `node_modules/react-native/scripts/xcode/...` but this directory does not contain that script
https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/xcode/ccache-clang.sh

image

### Steps to reproduce

N/A

### React Native Version

0.74.0-rc.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

### Screenshots and Videos

_No response_

### PR DESCRIPTION
**Pull request by cipolleschi**
## Summary:
This PR bumps hermes in 0.74. This is needed because we need the microTask queue that has been shipped in Hermes

## Changelog:
[Internal] - Bump Hermes

## Test Plan:
CCI is green again for `build_android`

### CODE REVIEW

File: packages/react-native/ReactCommon/jsi/jsi/decorator.h [hunk 1]
```diff
@@ -126,6 +126,9 @@ class RuntimeDecorator : public Base, private jsi::Instrumentation {
       const std::shared_ptr<const PreparedJavaScript>& js) override {
     return plain().evaluatePreparedJavaScript(js);
   }
+  void queueMicrotask(const jsi::Function& callback) override {
+    return plain().queueMicrotask(callback);
+  }
```
Comment (cipolleschi) [inline packages/react-native/ReactCommon/jsi/jsi/decorator.h:131]: https://github.com/facebook/hermes/commit/0a632b73b8386dfc9fde0ddca349919c20fe2852 adds this change in JSI. We need it in React Native as well

File: packages/react-native/ReactCommon/jsi/jsi/decorator.h [hunk 2]
```diff
@@ -544,6 +547,10 @@ class WithRuntimeDecorator : public RuntimeDecorator<Plain, Base> {
     Around around{with_};
     return RD::evaluatePreparedJavaScript(js);
   }
+  void queueMicrotask(const Function& callback) override {
```
Comment (cipolleschi) [inline packages/react-native/ReactCommon/jsi/jsi/decorator.h:550]: https://github.com/facebook/hermes/commit/0a632b73b8386dfc9fde0ddca349919c20fe2852 adds this change in JSI. We need it in React Native as well

File: packages/react-native/ReactCommon/jsi/jsi/jsi.h [hunk 3]
```diff
@@ -209,6 +209,13 @@ class JSI_EXPORT Runtime {
   virtual Value evaluatePreparedJavaScript(
       const std::shared_ptr<const PreparedJavaScript>& js) = 0;
 
+  /// Queues a microtask in the JavaScript VM internal Microtask (a.k.a. Job in
+  /// ECMA262) queue, to be executed when the host drains microtasks in
+  /// its event loop implementation.
+  ///
+  /// \param callback a function to be executed as a microtask.
+  virtual void queueMicrotask(const jsi::Function& callback) = 0;
```
Comment (cipolleschi) [inline packages/react-native/ReactCommon/jsi/jsi/jsi.h:217]: https://github.com/facebook/hermes/commit/7bda0c267e76d11b68a585f84cfdd65000babf85 adds this change in JSI. We need it in React Native as well
